import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/favicon144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/favicon72.png" />
        <link rel='icon' href='/favicon36.png' />
      </head>
      <body>{children}</body>
    </html>
  )
}
