/*
 * This file is generated by jOOQ.
 */
package xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.Player;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.PlayerBelong;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.PlayerHistory;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AthleticsTool extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/** The reference instance of <code>athletics-tool</code> */
	public static final AthleticsTool ATHLETICS_TOOL = new AthleticsTool();

	/** The table <code>athletics-tool.player</code>. */
	public final Player PLAYER = Player.PLAYER;

	/** The table <code>athletics-tool.player_belong</code>. */
	public final PlayerBelong PLAYER_BELONG = PlayerBelong.PLAYER_BELONG;

	/** The table <code>athletics-tool.player_history</code>. */
	public final PlayerHistory PLAYER_HISTORY = PlayerHistory.PLAYER_HISTORY;

	/** No further instances allowed */
	private AthleticsTool() {
		super("athletics-tool", null);
	}

	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(Player.PLAYER, PlayerBelong.PLAYER_BELONG, PlayerHistory.PLAYER_HISTORY);
	}
}
