/*
 * This file is generated by jOOQ.
 */
package xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.enums;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum PlayerHistoryCategory implements EnumType {
	senior("senior"),

	ordinary("ordinary"),

	college("college"),

	high_school("high-school"),

	junior("junior"),

	elementary("elementary");

	private final String literal;

	private PlayerHistoryCategory(String literal) {
		this.literal = literal;
	}

	@Override
	public Catalog getCatalog() {
		return null;
	}

	@Override
	public Schema getSchema() {
		return null;
	}

	@Override
	public String getName() {
		return null;
	}

	@Override
	public String getLiteral() {
		return literal;
	}

	/** Lookup a value of this EnumType by its literal */
	public static PlayerHistoryCategory lookupLiteral(String literal) {
		return EnumType.lookupLiteral(PlayerHistoryCategory.class, literal);
	}
}
