/*
 * This file is generated by jOOQ.
 */
package xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.enums;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum PlayerHistoryPrefecture implements EnumType {
	hokkaido("hokkaido"),

	saitama("saitama"),

	tokyo("tokyo");

	private final String literal;

	private PlayerHistoryPrefecture(String literal) {
		this.literal = literal;
	}

	@Override
	public Catalog getCatalog() {
		return null;
	}

	@Override
	public Schema getSchema() {
		return null;
	}

	@Override
	public String getName() {
		return null;
	}

	@Override
	public String getLiteral() {
		return literal;
	}

	/** Lookup a value of this EnumType by its literal */
	public static PlayerHistoryPrefecture lookupLiteral(String literal) {
		return EnumType.lookupLiteral(PlayerHistoryPrefecture.class, literal);
	}
}
