/*
 * This file is generated by jOOQ.
 */
package xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.records;

import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.PlayerBelong;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlayerBelongRecord extends UpdatableRecordImpl<PlayerBelongRecord>
		implements Record5<Integer, String, Byte, LocalDateTime, LocalDateTime> {

	private static final long serialVersionUID = 1L;

	/** Setter for <code>athletics-tool.player_belong.id</code>. */
	public void setId(Integer value) {
		set(0, value);
	}

	/** Getter for <code>athletics-tool.player_belong.id</code>. */
	public Integer getId() {
		return (Integer) get(0);
	}

	/** Setter for <code>athletics-tool.player_belong.name</code>. */
	public void setName(String value) {
		set(1, value);
	}

	/** Getter for <code>athletics-tool.player_belong.name</code>. */
	public String getName() {
		return (String) get(1);
	}

	/** Setter for <code>athletics-tool.player_belong.delete_flag</code>. */
	public void setDeleteFlag(Byte value) {
		set(2, value);
	}

	/** Getter for <code>athletics-tool.player_belong.delete_flag</code>. */
	public Byte getDeleteFlag() {
		return (Byte) get(2);
	}

	/** Setter for <code>athletics-tool.player_belong.created_at</code>. */
	public void setCreatedAt(LocalDateTime value) {
		set(3, value);
	}

	/** Getter for <code>athletics-tool.player_belong.created_at</code>. */
	public LocalDateTime getCreatedAt() {
		return (LocalDateTime) get(3);
	}

	/** Setter for <code>athletics-tool.player_belong.updated_at</code>. */
	public void setUpdatedAt(LocalDateTime value) {
		set(4, value);
	}

	/** Getter for <code>athletics-tool.player_belong.updated_at</code>. */
	public LocalDateTime getUpdatedAt() {
		return (LocalDateTime) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row5<Integer, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	@Override
	public Row5<Integer, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
		return (Row5) super.valuesRow();
	}

	@Override
	public Field<Integer> field1() {
		return PlayerBelong.PLAYER_BELONG.ID;
	}

	@Override
	public Field<String> field2() {
		return PlayerBelong.PLAYER_BELONG.NAME;
	}

	@Override
	public Field<Byte> field3() {
		return PlayerBelong.PLAYER_BELONG.DELETE_FLAG;
	}

	@Override
	public Field<LocalDateTime> field4() {
		return PlayerBelong.PLAYER_BELONG.CREATED_AT;
	}

	@Override
	public Field<LocalDateTime> field5() {
		return PlayerBelong.PLAYER_BELONG.UPDATED_AT;
	}

	@Override
	public Integer component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getName();
	}

	@Override
	public Byte component3() {
		return getDeleteFlag();
	}

	@Override
	public LocalDateTime component4() {
		return getCreatedAt();
	}

	@Override
	public LocalDateTime component5() {
		return getUpdatedAt();
	}

	@Override
	public Integer value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getName();
	}

	@Override
	public Byte value3() {
		return getDeleteFlag();
	}

	@Override
	public LocalDateTime value4() {
		return getCreatedAt();
	}

	@Override
	public LocalDateTime value5() {
		return getUpdatedAt();
	}

	@Override
	public PlayerBelongRecord value1(Integer value) {
		setId(value);
		return this;
	}

	@Override
	public PlayerBelongRecord value2(String value) {
		setName(value);
		return this;
	}

	@Override
	public PlayerBelongRecord value3(Byte value) {
		setDeleteFlag(value);
		return this;
	}

	@Override
	public PlayerBelongRecord value4(LocalDateTime value) {
		setCreatedAt(value);
		return this;
	}

	@Override
	public PlayerBelongRecord value5(LocalDateTime value) {
		setUpdatedAt(value);
		return this;
	}

	@Override
	public PlayerBelongRecord values(
			Integer value1, String value2, Byte value3, LocalDateTime value4, LocalDateTime value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/** Create a detached PlayerBelongRecord */
	public PlayerBelongRecord() {
		super(PlayerBelong.PLAYER_BELONG);
	}

	/** Create a detached, initialised PlayerBelongRecord */
	public PlayerBelongRecord(
			Integer id, String name, Byte deleteFlag, LocalDateTime createdAt, LocalDateTime updatedAt) {
		super(PlayerBelong.PLAYER_BELONG);

		setId(id);
		setName(name);
		setDeleteFlag(deleteFlag);
		setCreatedAt(createdAt);
		setUpdatedAt(updatedAt);
	}
}
