/*
 * This file is generated by jOOQ.
 */
package xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.records;

import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.enums.PlayerHistoryCategory;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.enums.PlayerHistoryPrefecture;
import xyz.walk8243.athleticstool.repositoryapi.infrastructure.database.entity.tables.PlayerHistory;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlayerHistoryRecord extends UpdatableRecordImpl<PlayerHistoryRecord>
		implements Record10<
				Integer,
				Integer,
				Integer,
				Integer,
				String,
				String,
				PlayerHistoryPrefecture,
				Integer,
				PlayerHistoryCategory,
				LocalDateTime> {

	private static final long serialVersionUID = 1L;

	/** Setter for <code>athletics-tool.player_history.id</code>. */
	public void setId(Integer value) {
		set(0, value);
	}

	/** Getter for <code>athletics-tool.player_history.id</code>. */
	public Integer getId() {
		return (Integer) get(0);
	}

	/** Setter for <code>athletics-tool.player_history.player_id</code>. */
	public void setPlayerId(Integer value) {
		set(1, value);
	}

	/** Getter for <code>athletics-tool.player_history.player_id</code>. */
	public Integer getPlayerId() {
		return (Integer) get(1);
	}

	/** Setter for <code>athletics-tool.player_history.history</code>. */
	public void setHistory(Integer value) {
		set(2, value);
	}

	/** Getter for <code>athletics-tool.player_history.history</code>. */
	public Integer getHistory() {
		return (Integer) get(2);
	}

	/** Setter for <code>athletics-tool.player_history.belong_id</code>. */
	public void setBelongId(Integer value) {
		set(3, value);
	}

	/** Getter for <code>athletics-tool.player_history.belong_id</code>. */
	public Integer getBelongId() {
		return (Integer) get(3);
	}

	/** Setter for <code>athletics-tool.player_history.name</code>. */
	public void setName(String value) {
		set(4, value);
	}

	/** Getter for <code>athletics-tool.player_history.name</code>. */
	public String getName() {
		return (String) get(4);
	}

	/** Setter for <code>athletics-tool.player_history.kana</code>. */
	public void setKana(String value) {
		set(5, value);
	}

	/** Getter for <code>athletics-tool.player_history.kana</code>. */
	public String getKana() {
		return (String) get(5);
	}

	/** Setter for <code>athletics-tool.player_history.prefecture</code>. */
	public void setPrefecture(PlayerHistoryPrefecture value) {
		set(6, value);
	}

	/** Getter for <code>athletics-tool.player_history.prefecture</code>. */
	public PlayerHistoryPrefecture getPrefecture() {
		return (PlayerHistoryPrefecture) get(6);
	}

	/** Setter for <code>athletics-tool.player_history.year</code>. */
	public void setYear(Integer value) {
		set(7, value);
	}

	/** Getter for <code>athletics-tool.player_history.year</code>. */
	public Integer getYear() {
		return (Integer) get(7);
	}

	/** Setter for <code>athletics-tool.player_history.category</code>. */
	public void setCategory(PlayerHistoryCategory value) {
		set(8, value);
	}

	/** Getter for <code>athletics-tool.player_history.category</code>. */
	public PlayerHistoryCategory getCategory() {
		return (PlayerHistoryCategory) get(8);
	}

	/** Setter for <code>athletics-tool.player_history.created_at</code>. */
	public void setCreatedAt(LocalDateTime value) {
		set(9, value);
	}

	/** Getter for <code>athletics-tool.player_history.created_at</code>. */
	public LocalDateTime getCreatedAt() {
		return (LocalDateTime) get(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row10<
					Integer,
					Integer,
					Integer,
					Integer,
					String,
					String,
					PlayerHistoryPrefecture,
					Integer,
					PlayerHistoryCategory,
					LocalDateTime>
			fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	@Override
	public Row10<
					Integer,
					Integer,
					Integer,
					Integer,
					String,
					String,
					PlayerHistoryPrefecture,
					Integer,
					PlayerHistoryCategory,
					LocalDateTime>
			valuesRow() {
		return (Row10) super.valuesRow();
	}

	@Override
	public Field<Integer> field1() {
		return PlayerHistory.PLAYER_HISTORY.ID;
	}

	@Override
	public Field<Integer> field2() {
		return PlayerHistory.PLAYER_HISTORY.PLAYER_ID;
	}

	@Override
	public Field<Integer> field3() {
		return PlayerHistory.PLAYER_HISTORY.HISTORY;
	}

	@Override
	public Field<Integer> field4() {
		return PlayerHistory.PLAYER_HISTORY.BELONG_ID;
	}

	@Override
	public Field<String> field5() {
		return PlayerHistory.PLAYER_HISTORY.NAME;
	}

	@Override
	public Field<String> field6() {
		return PlayerHistory.PLAYER_HISTORY.KANA;
	}

	@Override
	public Field<PlayerHistoryPrefecture> field7() {
		return PlayerHistory.PLAYER_HISTORY.PREFECTURE;
	}

	@Override
	public Field<Integer> field8() {
		return PlayerHistory.PLAYER_HISTORY.YEAR;
	}

	@Override
	public Field<PlayerHistoryCategory> field9() {
		return PlayerHistory.PLAYER_HISTORY.CATEGORY;
	}

	@Override
	public Field<LocalDateTime> field10() {
		return PlayerHistory.PLAYER_HISTORY.CREATED_AT;
	}

	@Override
	public Integer component1() {
		return getId();
	}

	@Override
	public Integer component2() {
		return getPlayerId();
	}

	@Override
	public Integer component3() {
		return getHistory();
	}

	@Override
	public Integer component4() {
		return getBelongId();
	}

	@Override
	public String component5() {
		return getName();
	}

	@Override
	public String component6() {
		return getKana();
	}

	@Override
	public PlayerHistoryPrefecture component7() {
		return getPrefecture();
	}

	@Override
	public Integer component8() {
		return getYear();
	}

	@Override
	public PlayerHistoryCategory component9() {
		return getCategory();
	}

	@Override
	public LocalDateTime component10() {
		return getCreatedAt();
	}

	@Override
	public Integer value1() {
		return getId();
	}

	@Override
	public Integer value2() {
		return getPlayerId();
	}

	@Override
	public Integer value3() {
		return getHistory();
	}

	@Override
	public Integer value4() {
		return getBelongId();
	}

	@Override
	public String value5() {
		return getName();
	}

	@Override
	public String value6() {
		return getKana();
	}

	@Override
	public PlayerHistoryPrefecture value7() {
		return getPrefecture();
	}

	@Override
	public Integer value8() {
		return getYear();
	}

	@Override
	public PlayerHistoryCategory value9() {
		return getCategory();
	}

	@Override
	public LocalDateTime value10() {
		return getCreatedAt();
	}

	@Override
	public PlayerHistoryRecord value1(Integer value) {
		setId(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value2(Integer value) {
		setPlayerId(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value3(Integer value) {
		setHistory(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value4(Integer value) {
		setBelongId(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value5(String value) {
		setName(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value6(String value) {
		setKana(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value7(PlayerHistoryPrefecture value) {
		setPrefecture(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value8(Integer value) {
		setYear(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value9(PlayerHistoryCategory value) {
		setCategory(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord value10(LocalDateTime value) {
		setCreatedAt(value);
		return this;
	}

	@Override
	public PlayerHistoryRecord values(
			Integer value1,
			Integer value2,
			Integer value3,
			Integer value4,
			String value5,
			String value6,
			PlayerHistoryPrefecture value7,
			Integer value8,
			PlayerHistoryCategory value9,
			LocalDateTime value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/** Create a detached PlayerHistoryRecord */
	public PlayerHistoryRecord() {
		super(PlayerHistory.PLAYER_HISTORY);
	}

	/** Create a detached, initialised PlayerHistoryRecord */
	public PlayerHistoryRecord(
			Integer id,
			Integer playerId,
			Integer history,
			Integer belongId,
			String name,
			String kana,
			PlayerHistoryPrefecture prefecture,
			Integer year,
			PlayerHistoryCategory category,
			LocalDateTime createdAt) {
		super(PlayerHistory.PLAYER_HISTORY);

		setId(id);
		setPlayerId(playerId);
		setHistory(history);
		setBelongId(belongId);
		setName(name);
		setKana(kana);
		setPrefecture(prefecture);
		setYear(year);
		setCategory(category);
		setCreatedAt(createdAt);
	}
}
