spring:
  application:
    name: athletics-tool-repository-api
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: false
  resources:
    add-mappings: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:mariadb://${DB_HOSTNAME}:${DB_PORT}/${DB_SCHEMA}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jooq:
    sql-dialect: MARIADB
