spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/athletics-tool
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: ${DB_PASSWORD}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
